### ISSUE TITLE
Questions Regarding Generation Weights Offloading and Buffer Usage

### ISSUE THREAD

**Issue by metaqiang** [volcengine/verl#25]
Hello Author,

First of all, thank you for your great work on this project. I have a couple of questions regarding the generation process that I hope you can clarify:

1. **Offloading Generation Weights to the CPU:**
   - **Why are the generation weights offloaded to the CPU?** My understanding is that during generation, the weights should remain consistent with those obtained after training. Therefore, I would expect the generation weights to directly utilize the trained weights rather than being reloaded from the CPU. Could you please explain the reasoning behind this approach?

2. **Use of Two Buffers During Generation:**
   - **Why are two buffers used in the generation process instead of one?** I noticed that the generation involves handling two separate buffers, and I'm curious about the benefits or requirements that necessitate this design choice. Is there a specific advantage to using two buffers over a single one?

![image](https://github.com/user-attachments/assets/f83b6857-2c0c-40cc-b00f-89957dd561d9)

I look forward to your insights on these matters. Thank you for your time and assistance!

**Comment by PeterSH6** [comment]
Hi @metaqiang ,

As you can see in Figure 8 of the Paper (and also `AllGatherPPModel` class in code), the model in generation typically has a smaller Model Parallel Size compared to the model used in training. Therefore, during generation, we need to gather the weights from other ranks to form a contiguous buffer.

In `AllGatherPPModel`, we maintain two buffers: one for training (`this_rank`) and another for storing the weights from other ranks (`cur_pp_rank != self.pp_rank`) for generation. This is what we refer to as the two buffers for training and generation.

When we offload the generation weights to the CPU, it means that after the generation process is complete, we only need to keep the parameters from `this_rank` for the training stage. The weights from `other_rank` which are used to form the generation weights, are no longer required. Therefore, we offload these weights to reduce peak memory usage.
