### ISSUE TITLE
Are optimizer states reloaded or offloaded during the conversion from actor training to actor rollout?

### ISSUE THREAD

**Issue by G1aZzz** [volcengine/verl#42]
hi veRL team, thanks for open-sourcing the great framework. I have some questions about conversion from actor training to rollout in verl.  I would greatly appreciate any insights or clarifications you can provide.

### Questions:
**Optimizer State Offload:**
During the conversion from actor training to actor rollout, is there an interface provided to offload/reload the optimizer states? 

Thanks!

**Comment by PeterSH6** [comment]
Hi @G1aZzz , do you mean the offload optimizer in Megatron backend? Offload optimizer is supported in FSDP.
