### ISSUE TITLE
whether the auto device mapping code in the paper has been uploaded?

### ISSUE THREAD

**Issue by Zeroreoo** [volcengine/verl#5]
The auto device mapping in chapter 6 is not found in the code. Is it that the related code has not been uploaded?

**Comment by PeterSH6** [comment]
Hi, the code for auto mapping is not uploaded as it incorporates in-house cost models, which are not able to be disclosed.

**Comment by eric-haibin-lin** [comment]
The auto device mapping is not released, but we provided a simple example to illustrate how to do it manually
https://github.com/volcengine/verl/tree/main/examples/split_placement
