### ISSUE TITLE
package confilct

### ISSUE THREAD

**Issue by hljjjmssyh** [volcengine/verl#62]
ERROR: pip's dependency resolver does not currently take into account all the packages that are installed. This behaviour is the source of the following dependency conflicts.
tensordict 0.6.2 requires torch>=2.5.0, but you have torch 2.4.0+cu124 which is incompatible.

**Comment by eric-haibin-lin** [comment]
Should be fixed by https://github.com/volcengine/verl/pull/59, tensordict limited to v0.5 https://github.com/pytorch/tensordict/blob/v0.5.0/setup.py#L72 
The torch version is required by vllm.
