### ISSUE TITLE
Missing doc about "Algorithm Baselines"

### ISSUE THREAD

**Issue by fzyzcjy** [volcengine/verl#66]
Hi thanks for the lib, but it seems when clicking links in https://verl.readthedocs.io/en/latest/experiment/ppo.html, it gives 404, e.g. 

![image](https://github.com/user-attachments/assets/41a218b7-6108-49ba-9911-928192c66ede)

**Comment by eric-haibin-lin** [comment]
There's some rendering issue. Fixed now. Thanks for reporting!

**Comment by fzyzcjy** [comment]
You are welcome!

**Comment by eric-haibin-lin** [comment]
@fzyzcjy BTW what's the RAM/GPU setup you have? I am preparing an example that only uses minimal CPU/GPU memory, for members who do not have a lot of compute resources. It seems that verl need more than 16GB of CPU RAM for the example before optimization and I wonder what's would be a common case

**Comment by fzyzcjy** [comment]
@eric-haibin-lin My personal setup is 4090D + 64G cpu memory.

**Comment by eric-haibin-lin** [comment]
Just created this notebook and it seems like 24GB GPU memory is sufficient:
https://github.com/volcengine/verl/pull/92

**Comment by fzyzcjy** [comment]
That looks great! I will try to see whether there are rooms for speed optimizations later on my 24G card as well.
