### ISSUE TITLE
Docker image support

### ISSUE THREAD

**Issue by SolenoidWGT** [volcengine/verl#8]
Thank for your great work! We encountered some version issues when running verl+megatron on our cluster. We noticed that verl does not provide an official dockerfile or image link. Any plan to add this? We are looking forward to it.

**Comment by PeterSH6** [comment]
Good suggestion. We will provide an dockerfile for installation.

For the version error, could you post the errors here? So that I can investigate what's the problem.

**Comment by eric-haibin-lin** [comment]
@SolenoidWGT I'm working on it, will give an update in 1-2 days

**Comment by eric-haibin-lin** [comment]
it's a bit late but late is better than never..
https://github.com/volcengine/verl/pull/41 @SolenoidWGT
